
title: Flickorz 3D Collections
description: Flickorz 3D Collections - Art work, arttoy made in Blender
baseurl: "/collections"  # Set the baseurl to the subdirectory
url: "https://flickorz.github.io"  # The main domain for your site
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
